<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 10.18 view script
 * 
 * @package    Application
 */

?>
<div class="row">
<div class="span9">
<h1>Listing 10.18</h1>
<h3><code>composer.json</code> für Installation des DoctrineORMModule</h3>
<pre>
{
    [...]
    "minimum-stability": "alpha",
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.1.*",
        "doctrine/doctrine-orm-module": "0.*"
    }
}

</pre>
</div>
</div>
