<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 10.17 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.17</h1>
<h3><code>RowGatewayFeature</code> mit <code>TableGateway</code> und <code>RowGateway</code> einsetzen</h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\Db\TableGateway\Feature\RowGatewayFeature;
use Zend\Debug\Debug;
use Pizza\Entity\ToppingEntity;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$rowGatewayFeature = new RowGatewayFeature('id');

$toppingsTable = new TableGateway('toppings', $db, $rowGatewayFeature);

$rows = $toppingsTable->select(array('costs' => 1.5));

foreach ($rows as $row) {
    Debug::dump('Belag ' . $row->name . ' kostet ' . $row->costs . '€');
}
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\Db\TableGateway\Feature\RowGatewayFeature;
use Zend\Debug\Debug;
use Pizza\Entity\ToppingEntity;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$rowGatewayFeature = new RowGatewayFeature('id');

$toppingsTable = new TableGateway('toppings', $db, $rowGatewayFeature);

$rows = $toppingsTable->select(array('costs' => 1.5));

foreach ($rows as $row) {
    Debug::dump('Belag ' . $row->name . ': ' . $row->costs . '€');
}
?>
</div>
</div>
