<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.11 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.11</h1>
<h3>Schreibende Abfragen mit <code>Zend\Db\Sql</code> generieren</h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Sql;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$sql = new Sql($db);

$insert = $sql->insert('crusts');
$insert->columns(array('name', 'costs'));
$insert->values(array(
    'name'  => 'Pizzaboden aus Dnikelmehl',
    'costs' => 2.5,
));

$db->query($sql->getSqlStringForSqlObject($insert), Adapter::QUERY_MODE_EXECUTE);

$id = $db->getDriver()->getLastGeneratedValue();

$update = $sql->update('crusts');
$update->set(array(
    'name'  => 'Pizzaboden aus Dinkelmehl',
));
$update->where->equalTo('id', $id);

$db->query($sql->getSqlStringForSqlObject($update), Adapter::QUERY_MODE_EXECUTE);

$delete = $sql->delete('crusts');
$delete->where->equalTo('id', $id);

$db->query($sql->getSqlStringForSqlObject($delete), Adapter::QUERY_MODE_EXECUTE);

Debug::dump($sql->getSqlStringForSqlObject($insert));
Debug::dump($sql->getSqlStringForSqlObject($update));
Debug::dump($sql->getSqlStringForSqlObject($delete));
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Sql;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$sql = new Sql($db);

$insert = $sql->insert('crusts');
$insert->columns(array('name', 'costs'));
$insert->values(array(
    'name'  => 'Pizzaboden aus Dnikelmehl',
    'costs' => 2.5,
));

$db->query($sql->getSqlStringForSqlObject($insert), Adapter::QUERY_MODE_EXECUTE);

$id = $db->getDriver()->getLastGeneratedValue();

$update = $sql->update('crusts');
$update->set(array(
        'name'  => 'Pizzaboden aus Dinkelmehl',
));
$update->where->equalTo('id', $id);

$db->query($sql->getSqlStringForSqlObject($update), Adapter::QUERY_MODE_EXECUTE);

$delete = $sql->delete('crusts');
$delete->where->equalTo('id', $id);

$db->query($sql->getSqlStringForSqlObject($delete), Adapter::QUERY_MODE_EXECUTE);

Debug::dump($sql->getSqlStringForSqlObject($insert));
Debug::dump($sql->getSqlStringForSqlObject($update));
Debug::dump($sql->getSqlStringForSqlObject($delete));
?>
</div>
</div>
