<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 10.21 view script
 * 
 * @package    Application
 */

?>
<div class="row">
<div class="span9">
<h1>Listing 10.21</h1>
<h3><code>PizzaEntity</code> Klasse für den Einsatz mit Doctrine 2</h3>
<pre>
&lt;?php
namespace Pizza\Doctrine;

use Doctrine\ORM\Mapping as ORM;

/**
 * Pizza entity
 *
 * @package Pizza
 *         
 * @ORM\Entity
 * @ORM\Table(name="pizzas")
 * @property string $name
 * @property string $price
 * @property int $id
 */
class PizzaEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer");
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="string")
     */
    protected $name;
    
    /**
     * @ORM\Column(type="string")
     */
    protected $price;
    
    /**
     * @ORM\OneToOne(targetEntity="CrustEntity")
     * @ORM\JoinColumn(name="crust_id", referencedColumnName="id")
     **/
    private $crust;

    /**
     * @ORM\ManyToMany(targetEntity="ToppingEntity")
     * @ORM\JoinTable(name="pizzas_toppings",
     *      joinColumns={
     *          @ORM\JoinColumn(name="pizza_id", referencedColumnName="id")
     *      },
     *      inverseJoinColumns={
     *          @ORM\JoinColumn(
     *              name="topping_id", referencedColumnName="id", unique=true
     *          )
     *      }
     * )
     **/
    private $toppings;
    
    public function __get ($property)
    {
        return $this->$property;
    }

    public function __set ($property, $value)
    {
        $this->$property = $value;
    }

    public function getArrayCopy ()
    {
        $data = array(
            'id'       => $this->id,
            'name'     => $this->name,
            'price'    => $this->price,
            'crust'    => $this->crust->getArrayCopy(),
            'toppings' => array(),
        );
        
        foreach ($this->toppings as $topping) {
            $data['toppings'][] = $topping->getArrayCopy();
        }
        
        return $data;
    }

    public function populate ($data = array())
    {
        $this->id       = $data['id'      ];
        $this->name     = $data['name'    ];
        $this->price    = $data['price'   ];
        $this->crust    = $data['crust'   ];
        $this->toppings = $data['toppings'];
    }
}
</pre>
</div>
</div>
