<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.13 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.13</h1>
<h3>Einsatz von <code>TableGateway</code> mit <code>select()</code> und <code>selectWith()</code></h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;
use Pizza\Entity\ToppingEntity;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$resultSetPrototype = new ResultSet(
    ResultSet::TYPE_ARRAYOBJECT, new ToppingEntity()
);

$toppingsTable = new TableGateway('toppings', $db, null, $resultSetPrototype);

$rows = $toppingsTable->select(array('costs' => 1.5));

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}

echo '&lt;hr /&gt;';

$select = $toppingsTable->getSql()->select();
$select->where->greaterThanOrEqualTo('costs', 1.5);
$select->where->like('name', '%a%');
$select->where->in('id', array(10, 12, 5, 6));
$select->order(array('name'  => 'DESC'));

$rows = $toppingsTable->selectWith($select);

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Db\ResultSet\ResultSet;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;
use Pizza\Entity\ToppingEntity;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$resultSetPrototype = new ResultSet(
    ResultSet::TYPE_ARRAYOBJECT, new ToppingEntity()
);

$toppingsTable = new TableGateway('toppings', $db, null, $resultSetPrototype);

$rows = $toppingsTable->select(array('costs' => 1.5));

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}

echo '<hr />';

$select = $toppingsTable->getSql()->select();
$select->where->greaterThanOrEqualTo('costs', 1.5);
$select->where->like('name', '%a%');
$select->where->in('id', array(10, 12, 5, 6));
$select->order(array('name'  => 'DESC'));

$rows = $toppingsTable->selectWith($select);

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}
?>
</div>
</div>
