<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.12</h1>
<h3>Tabellen anlegen, ändern und löschen mit <code>Zend\Db\Sql\Ddl</code> generieren</h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Ddl\Column\Char;
use Zend\Db\Sql\Ddl\Column\Date;
use Zend\Db\Sql\Ddl\Column\Float;
use Zend\Db\Sql\Ddl\Column\Integer;
use Zend\Db\Sql\Ddl\Column\Varchar;
use Zend\Db\Sql\Ddl\Constraint\PrimaryKey;
use Zend\Db\Sql\Ddl\AlterTable;
use Zend\Db\Sql\Ddl\CreateTable;
use Zend\Db\Sql\Ddl\DropTable;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$columnId   = new Integer('id');
$columnDate = new Date('created');
$columnSum  = new Float('sum', 6, 2);
$columnCode = new Char('code', 3);
$columnName = new Varchar('name', 64);
$primary    = new PrimaryKey('id');

$create = new CreateTable('orders');
$create->addColumn($columnId);
$create->addColumn($columnDate);
$create->addColumn($columnSum);
$create->addColumn($columnCode);

$alter = new AlterTable('orders');
$alter->addColumn($columnName);
$alter->addConstraint($primary);
$alter->dropColumn('code');

$drop = new DropTable('orders');

Debug::dump($create->getSqlString());
Debug::dump($alter->getSqlString());
Debug::dump($drop->getSqlString());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\Db\Adapter\Adapter;
use Zend\Db\Sql\Ddl\Column\Char;
use Zend\Db\Sql\Ddl\Column\Date;
use Zend\Db\Sql\Ddl\Column\Float;
use Zend\Db\Sql\Ddl\Column\Integer;
use Zend\Db\Sql\Ddl\Column\Varchar;
use Zend\Db\Sql\Ddl\Constraint\PrimaryKey;
use Zend\Db\Sql\Ddl\AlterTable;
use Zend\Db\Sql\Ddl\CreateTable;
use Zend\Db\Sql\Ddl\DropTable;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$columnId   = new Integer('id');
$columnDate = new Date('created');
$columnSum  = new Float('sum', 6, 2);
$columnCode = new Char('code', 3);
$columnName = new Varchar('name', 64);
$primary    = new PrimaryKey('id');

$create = new CreateTable('orders');
$create->addColumn($columnId);
$create->addColumn($columnDate);
$create->addColumn($columnSum);
$create->addColumn($columnCode);

$alter = new AlterTable('orders');
$alter->addColumn($columnName);
$alter->addConstraint($primary);
$alter->dropColumn('code');

$drop = new DropTable('orders');

Debug::dump($create->getSqlString());
Debug::dump($alter->getSqlString());
Debug::dump($drop->getSqlString());
?>
</div>
</div>
