<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 10.1 view script
 * 
 * @package    Application
 */

?>
<div class="row">
<div class="span9">
<h1>Listing 10.1</h1>
<h3>Initialisierung eines Datenbankadapters für SQLite3</h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$config = array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
);

$db = new Adapter($config);

Debug::dump($db->getPlatform()->getName());
Debug::dump($db->getDriver()->getConnection());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$config = array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
);

$db = new Adapter($config);

Debug::dump($db->getPlatform()->getName());
Debug::dump($db->getDriver()->getConnection());
?>
</div>
</div>
