<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.14 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.14</h1>
<h3>Einsatz von <code>TableGateway</code> mit <code>insert()</code> und <code>delete()</code></h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$crustsTable = new TableGateway('crusts', $db);

$crustsTable->insert(array(
    'name'  => 'Pizzaboden aus Dinkelmehl',
    'costs' => 2.5,
));

$id = $db->getDriver()->getLastGeneratedValue();

$rows = $crustsTable->select(array(
    'id' => $id
));

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}

$crustsTable->delete(array(
    'id' => $id
));

$rows = $crustsTable->select(array('id' => $id));
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Db\TableGateway\TableGateway;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$crustsTable = new TableGateway('crusts', $db);

$crustsTable->insert(array(
    'name'  => 'Pizzaboden aus Dinkelmehl',
    'costs' => 2.5,
));

$id = $db->getDriver()->getLastGeneratedValue();

$rows = $crustsTable->select(array(
    'id' => $id
));

foreach ($rows as $row) {
    Debug::dump($row->getArrayCopy());
}

$crustsTable->delete(array(
    'id' => $id
));

$rows = $crustsTable->select(array('id' => $id));
?>
</div>
</div>
