<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.2</h1>
<h3>Initialisierung eines Datenbankadapters für MySQL</h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$config = array(
    'driver'  => 'Pdo',
    'dsn'     => 'mysql:dbname=luigis-pizza;host=localhost;charset=utf8',
    'user'    => 'luigis-pizza',
    'pass'    => 'luigis-pizza',
);

$db = new Adapter($config);

Debug::dump($db->getPlatform()->getName());
Debug::dump($db->getDriver()->getConnection());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$config = array(
    'driver'  => 'Pdo',
    'dsn'     => 'mysql:dbname=luigis-pizza;host=localhost;charset=utf8',
    'user'    => 'luigis-pizza',
    'pass'    => 'luigis-pizza',
);

$db = new Adapter($config);

Debug::dump($db->getPlatform()->getName());
Debug::dump($db->getDriver()->getConnection());
?>
</div>
</div>
