<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 10.14 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.14</h1>
<h3><code>LogListener</code> zum Loggen der <code>TableGateway</code> Events</h3>
<pre>
&lt;?php
namespace Pizza\Listener;

use Zend\Db\TableGateway\Feature\EventFeature\TableGatewayEvent;
use Zend\EventManager\EventInterface;
use Zend\EventManager\EventManagerInterface;
use Zend\EventManager\ListenerAggregateInterface;
use Zend\Log\Logger;
use Zend\Log\Writer\Stream;

class LogListener implements ListenerAggregateInterface
{
    protected $logger = null;

    protected $listeners = array();

    public function __construct($file)
    {
        $this->logger = new Logger();
        $this->logger->addWriter(new Stream($file));
    }
    
    public function attach(EventManagerInterface $events)
    {
        $this->listeners[] = $events->attach('postInitialize', array($this, 'logPostInitialize'));
        $this->listeners[] = $events->attach('postInsert', array($this, 'logPostInsert'));
        $this->listeners[] = $events->attach('postDelete', array($this, 'logPostDelete'));
    }

    public function detach(EventManagerInterface $events)
    {
        foreach ($this->listeners as $index => $listener) {
            if ($events->detach($listener)) {
                unset($this->listeners[$index]);
            }
        }
    }

    public function logPostInitialize(TableGatewayEvent $e)
    {
        $this->logger->log(
            Logger::INFO, 
            'TableGateway für Tabelle "' . $e->getTarget()->getTable() 
                . '" initialisiert'
        );
    }

    public function logPostInsert(TableGatewayEvent $e)
    {
        $driver = $e->getTarget()->getAdapter()->getDriver();
        $params = $e->getParam('statement')->getParameterContainer();
        $id     = $driver->getLastGeneratedValue();
        
        $this->logger->log(
            Logger::INFO, 
            '"' . $params->offsetGet('name') . '" mit ID "' . $id 
                . '" in Tabelle "' . $e->getTarget()->getTable() 
                . '" eingefügt'
        );
    }

    public function logPostDelete(TableGatewayEvent $e)
    {
        $params = $e->getParam('statement')->getParameterContainer();
        
        $this->logger->log(
            Logger::INFO, 
            'Datensatz mit ID "' . $params->offsetGet('where1') 
                . '" aus Tabelle "' . $e->getTarget()->getTable() 
                . '" gelöscht'
        );
    }
}
</pre>
</div>
</div>
