<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 10.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 10.3</h1>
<h3>Datenbankabfrage mit <code>query()</code></h3>
<pre>
&lt;?php
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$result = $db->query('SELECT * FROM toppings;', Adapter::QUERY_MODE_EXECUTE);

foreach ($result as $row) {
    Debug::dump($row->getArrayCopy());
}
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Db\Adapter\Adapter;
use Zend\Debug\Debug;

$db = new Adapter(array(
    'driver'   => 'Pdo_Sqlite',
    'database' => LUIGI_ROOT . '/data/db/pizza.sqlite3.db',
));

$result = $db->query('SELECT * FROM toppings;', Adapter::QUERY_MODE_EXECUTE);

foreach ($result as $row) {
    Debug::dump($row->getArrayCopy());
}
?>
</div>
</div>
