<?php 
/**
 * ZF2 Buch Kapitel 10
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 10</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1001">Listing 10.1</a></td>
<td>Initialisierung eines Datenbankadapters für SQLite3</td>
</tr>
<tr>
<td><a href="/listing/listing1002">Listing 10.2</a></td>
<td>Initialisierung eines Datenbankadapters für MySQL</td>
</tr>
<tr>
<td><a href="/listing/listing1003">Listing 10.3</a></td>
<td>Datenbankabfrage mit <code>query()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1004">Listing 10.4</a></td>
<td>Datenbankabfrage mit <code>createStatement()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1005">Listing 10.5</a></td>
<td>Schreibende Anfragen mit Datenbankadapter</td>
</tr>
<tr>
<td><a href="/listing/listing1006">Listing 10.6</a></td>
<td>Entität für Pizzaböden</td>
</tr>
<tr>
<td><a href="/listing/listing1007">Listing 10.7</a></td>
<td><code>CrustEntity</code> als ResultSet für Abfrage zurückerhalten</td>
</tr>
<tr>
<td><a href="/listing/listing1008">Listing 10.8</a></td>
<td>Einfache <code>SELECT</code>-Abfrage mit <code>Zend\Db\Sql</code></td>
</tr>
<tr>
<td><a href="/listing/listing1009">Listing 10.9</a></td>
<td><code>SELECT</code>-Abfrage mit <code>JOIN</code> und Einsatz eines Statement-Objekts</td>
</tr>
<tr>
<td><a href="/listing/listing1010">Listing 10.10</a></td>
<td><code>SELECT</code>-Abfrage mit erweiterter <code>WHERE</code>-Klausel</td>
</tr>
<tr>
<td><a href="/listing/listing1011">Listing 10.11</a></td>
<td>Schreibende Abfragen mit <code>Zend\Db\Sql</code> generieren</td>
</tr>
<tr>
<td><a href="/listing/listing1012">Listing 10.12</a></td>
<td>Tabellen anlegen, ändern und löschen mit <code>Zend\Db\Sql\Ddl</code> generieren</td>
</tr>
<tr>
<td><a href="/listing/listing1013">Listing 10.13</a></td>
<td>Einsatz von <code>TableGateway</code> mit <code>select()</code> und <code>selectWith()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1014">Listing 10.14</a></td>
<td>Einsatz von <code>TableGateway</code> mit <code>insert()</code> und <code>delete()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1015">Listing 10.15</a></td>
<td><code>LogListener</code> zum Loggen der <code>TableGateway</code> Events</td>
</tr>
<tr>
<td><a href="/listing/listing1016">Listing 10.16</a></td>
<td><code>EventFeature</code> mit <code>TableGateway</code> und <code>LogListener</code> einsetzen</td>
</tr>
<tr>
<td><a href="/listing/listing1017">Listing 10.17</a></td>
<td>Einsatz von <code>RowGateway</code> mit <code>save()</code> und <code>delete()</code></td>
</tr>
<tr>
<td><a href="/listing/listing1018">Listing 10.18</a></td>
<td><code>RowGatewayFeature</code> mit <code>TableGateway</code> und <code>RowGateway</code> einsetzen</td>
</tr>
<tr>
<td><a href="/listing/listing1019">Listing 10.19</a></td>
<td><code>composer.json</code> für Installation des DoctrineORMModule</td>
</tr>
<tr>
<td><a href="/listing/listing1020">Listing 10.20</a></td>
<td>Konfiguration der Doctrine 2 Verbindung in <code>global.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing1021">Listing 10.21</a></td>
<td>Doctrine 2 Konfiguration für <code>Pizza</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1022">Listing 10.22</a></td>
<td><code>PizzaEntity</code> Klasse für den Einsatz mit Doctrine 2</td>
</tr>
<tr>
<td><a href="/listing/listing1023">Listing 10.23</a></td>
<td>Ausgabe von Pizzadaten mit Doctrine 2</td>
</tr>
</tbody>
</table>
